BookStore.App/Models/Author.cs
namespace BookStore.App.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string Name { get; set; }

        //Relationships
        public List<Book> Books { get; set; } = new List<Book>();
    }
}

BookStore.App/Models/Book.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookStore.App.Models
{
    public class Book
    {
        public int Id { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage ="Title is required")]
        public string Title { get; set; }


        [Display(Name = "PublshedYear")]
        [Required(ErrorMessage = "Published Year is required")]
        public int PublishedYear { get; set; }

        [Display(Name = "NrOfPages")]
        [Required(ErrorMessage = "Number of pages is required")]
        public int NrOfPages { get; set; }


        [Display(Name = "URLimg")]
        [Required(ErrorMessage = "URLimg of pages is required")]
        public string  URLimg{ get; set; }


        //Relationships
        public int AuthorId { get; set; }
        public Author Author { get; set; }

    }
}

BookStore.App/Models/ErrorViewModel.cs
namespace BookStore.App.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookStore.App/ViewModels/GetBookVM.cs
using BookStore.App.Models;

namespace BookStore.App.ViewModels
{
    public class GetBookVM
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string URLimg { get; set; }

        public Author Author { get; set; }

    }
}

BookStore.App/ViewModels/PostBookVM.cs
using BookStore.App.Models;

namespace BookStore.App.ViewModels
{
    public class PostBookVM
    {
        public Book Book { get; set; } = new Book();
        public List<Author> Authors { get; set; } = new List<Author>();
    }
}

BookStore.App/Controllers/AuthorController.cs
using AuthorStore.App.Services;
using BookStore.App.Models;
using Microsoft.AspNetCore.Mvc;

namespace AuthorStore.App.Controllers
{
    public class AuthorController : Controller
    {
        private IAuthorServices _authorServices;

        public AuthorController(IAuthorServices authorsServices) => _authorServices = authorsServices;
        public async Task<IActionResult> Index()
        {
            var allAuthors = await _authorServices.GetAllAuthorsAsync();

            return View(allAuthors);
        }

        public async Task<IActionResult> Details(int id)
        {
            var author = await _authorServices.GetAuthorByIdAsync(id);
            return View(author);
        }
        //Create
        public async Task<IActionResult> Create()
        {
            var newAuthor = new Author();
            return View(newAuthor);
        }

        [HttpPost]
        public async Task<IActionResult> CreateConfirm([Bind("Name")] Author createAuthor)
        {
            if (!ModelState.IsValid)
            {
                return View(createAuthor);
            }
            await _authorServices.CreateAsync(createAuthor);
            return RedirectToAction(nameof(Index));
        }



        //Get: Authors/Modify/1
        public async Task<IActionResult> Modify(int id)
        {
            var authorDetails = await _authorServices.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> ModifyConfirm(int id , [Bind("Name")] Author newauthor)
        {
            if (!ModelState.IsValid)
            {
                return View(newauthor);
            }
            await _authorServices.ModifyAsync(id, newauthor);
            return RedirectToAction(nameof(Index));
        }
        ///delete mv
        public async Task<IActionResult> Delete(int id )
        {
            var authorDetails = await _authorServices.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var authorDetails= await _authorServices.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");

            await _authorServices.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

BookStore.App/Controllers/BookController.cs
using AuthorStore.App.Services;
using BookStore.App.Models;
using BookStore.App.Services;
using BookStore.App.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.App.Controllers
{
    public class BookController : Controller
    {
        private IBookServices _bookServices;
        private IAuthorServices _authorServices;

        public BookController(IBookServices booksServices, IAuthorServices authorServices)
        {
            _bookServices = booksServices;
            _authorServices = authorServices;
        }
        public IActionResult Index()
        {
            var allBooks = _bookServices.GetAllBooks();
            return View(allBooks);
        }

        public IActionResult Details(int id)
        {
            var book = _bookServices.GetBookById(id);


            return View(book);
        }
        //Create
        public IActionResult Create()
        {
            var allAuthors = _authorServices.GetAllAuthors();
            var newPostBookVM = new PostBookVM()
            {
                Authors = allAuthors
            };

            return View(newPostBookVM);
        }

        [HttpPost]
        public IActionResult CreateConfirm(PostBookVM createBook)
        {
            ModelState.Remove("Book.Author");
            if (!ModelState.IsValid)
            {
                return View(createBook);
            }
            _bookServices.Create(createBook.Book);
            return RedirectToAction(nameof(Index));
        }





        //Get: Books/Modify/1
        public IActionResult Modify(int id)
        {
            var bookDetails = _bookServices.GetBookById(id);
            if (bookDetails == null) return View("NotFound");
            return View(bookDetails);
        }

        [HttpPost]
        public IActionResult ModifyConfirm(int id , [Bind("Title,Author,PublishedYear,NrOfPages,URLimg")] Book newbook)
        {
            if (!ModelState.IsValid)
            {
                return View(newbook);
            }
            _bookServices.Modify(id, newbook);
            return RedirectToAction(nameof(Index));
        }
        ///delete mv
        public IActionResult Delete(int id )
        {
            var bookDetails =  _bookServices.GetBookById(id);
            if (bookDetails == null) return View("NotFound");
            return View(bookDetails);
        }

        [HttpPost, ActionName("Delete")]
        public  IActionResult DeleteConfirm(int id)
        {
            var bookDetails =  _bookServices.GetBookById(id);
            if (bookDetails == null) return View("NotFound");

            _bookServices.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

BookStore.App/Controllers/HomeController.cs
using BookStore.App.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookStore.App.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

BookStore.App/Views/Author/Create.cshtml
@model Author

@{
    ViewData["Title"] = "Add a new author";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Author</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="CreateConfirm">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input type="hidden" asp-for="Id" class="form-control" />

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Add" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BookStore.App/Views/Author/Delete.cshtml
@model Author

<h1>Are you sure that you want to delete this author? </h1>
<div class="card">
    <div class="card-header">
        @Model.Name
    </div>
    <div class="card-body">
        <h5 class="card-title"> @Model.Name</h5>
    </div>
   
    <div class="form-group">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id"/>
            <input type="submit" value="Confirm" class="btn btn-danger float-right"/>
        </form>
        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
    </div>
</div>

BookStore.App/Views/Author/Details.cshtml
@model Author

<h1>Details</h1>

<div class="card">
    <div class="card-header">
        @Model.Name
    </div

    <div class="card-body">
        <h5 class="card-title"> @Model.Name</h5>
    </div>
   
    <div>
         <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
    </div>
</div>

BookStore.App/Views/Author/Index.cshtml
@model List<Author>

<h1>All my books</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>

            <th scope="col">Name</th>
            <th scope="col">Books</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var author in Model)
        {
            <tr>
                <th scope="row">@author.Id</th>
                <td>@author.Name</td>
                <td>@string.Join(",", author.Books.Select(n => n.Title))</td>
                <td>
                    <a asp-controller="Author"
                       asp-action="Modify"
                       asp-route-id="@author.Id"
                       class="btn btn-primary">
                        Modify
                    </a>
                    <a 
                        asp-controller="Author" 
                        asp-action="Details" 
                        asp-route-id="@author.Id"
                        class="btn btn-primary">
                        Show details
                    </a>
                    <a asp-controller="Author"
                       asp-action="Delete"
                       asp-route-id="@author.Id"
                       class=" btn btn-danger">
                        Delete
                    </a>
                </td>
               
               
               
            </tr>
        }
    </tbody>
</table>

BookStore.App/Views/Author/Modify.cshtml
@model Author

@{
    ViewData["Title"] = "Update author";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update Author</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="ModifyConfirm">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input  type="hidden" asp-for="Id" class="form-control"  />

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BookStore.App/Views/Book/Create.cshtml
@model PostBookVM

@{
    ViewData["Title"] = "Add a new book";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Book</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="CreateConfirm">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input type="hidden" asp-for="@Model.Book.Id" class="form-control" />

                    <div class="form-group">
                        <label asp-for="@Model.Book.Title" class="control-label"></label>
                        <input asp-for="@Model.Book.Title" class="form-control" />
                        <span asp-validation-for="@Model.Book.Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Book.AuthorId" class="control-label"></label>
                        @* <input asp-for="Author" class="form-control" /> *@

                        <select class="form-select" asp-for="@Model.Book.AuthorId" aria-label="Default select example">
                            <option selected>Select author</option>
                            @foreach(var author in Model.Authors)
                            {
                                <option value="@author.Id">@author.Name</option>
                            }
                        </select>

                        <span asp-validation-for="@Model.Book.AuthorId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Book.URLimg" class="control-label"></label>
                        <input asp-for="@Model.Book.URLimg" class="form-control" />
                        <span asp-validation-for="@Model.Book.URLimg" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Book.PublishedYear" class="control-label"></label>
                        <input asp-for="@Model.Book.PublishedYear" class="form-control" />
                        <span asp-validation-for="@Model.Book.PublishedYear" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Book.NrOfPages" class="control-label"></label>
                        <input asp-for="@Model.Book.NrOfPages" class="form-control" />
                        <span asp-validation-for="@Model.Book.NrOfPages" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Add" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BookStore.App/Views/Book/Delete.cshtml
@model Book

<h1>Are you sure that you want to delete this book? </h1>
<div class="card">
    <div class="card-header">
        @Model.Title
    </div>
    <div class="card-body">
        <h5 class="card-title"> @Model.Title</h5>
        @* <p class="card-text">@Model.Author</p> *@
        <hr />
        <p class="card-text"><b>Number of pages:</b> @Model.NrOfPages</p>
        <p class="card-text"><b>Published year:</b> @Model.PublishedYear</p>
    </div>
    <div class="form-group text-center">
        <img src="@Url.Content(Model.URLimg)" width="50" />

    </div>
    <div class="form-group">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id"/>
            <input type="submit" value="Confirm" class="btn btn-danger float-right"/>
        </form>
        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
    </div>
</div>

BookStore.App/Views/Book/Details.cshtml
@model Book

<h1>Details</h1>

<div class="card">
    <div class="card-header">
        @Model.Title
    </div

    <div class="card-body">
        <h5 class="card-title"> @Model.Title</h5>
        @* <p class="card-text">@Model.Author</p> *@
        <hr />
        <p class="card-text"><b>Number of pages:</b> @Model.NrOfPages</p>
        <p class="card-text"><b>Published year:</b> @Model.PublishedYear</p
    </div>
    <div class="form-group text-center">
                              <img src="@Url.Content(Model.URLimg)" width="50"/>
    </div>
    <div>
         <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
    </div>
</div>

BookStore.App/Views/Book/Index.cshtml
@model List<Book>

<h1>All my books</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>

            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Profile Picture</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var book in Model)
        {
            <tr>
                <th scope="row">@book.Id</th>
                <td>@book.Title</td>
                <td>@book.Author.Name</td>
                <td>
                    <img src="@Url.Content(book.URLimg)" width="50"/>
                </td>
                <td>
                    <a asp-controller="Book"
                       asp-action="Modify"
                       asp-route-id="@book.Id"
                       class="btn btn-primary">
                        Modify
                    </a>
                    <a 
                        asp-controller="Book" 
                        asp-action="Details" 
                        asp-route-id="@book.Id"
                        class="btn btn-primary">
                        Show details
                    </a>
                    <a asp-controller="Book"
                       asp-action="Delete"
                       asp-route-id="@book.Id"
                       class=" btn btn-danger">
                        Delete
                    </a>
                </td>
               
               
               
            </tr>
        }
    </tbody>
</table>

BookStore.App/Views/Book/Modify.cshtml
@model Book

@{
    ViewData["Title"] = "Update book";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update Book</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="ModifyConfirm">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input  type="hidden" asp-for="Id" class="form-control"  />

                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    @* <div class="form-group">
                        <label asp-for="Author" class="control-label"></label>
                        <input asp-for="Author" class="form-control" />
                        <span asp-validation-for="Author" class="text-danger"></span>
                    </div> *@
                    <div class="form-group">
                    <label asp-for="URLimg" class="control-label"></label>
                    <input asp-for="URLimg" class="form-control" />
                    <span asp-validation-for="URLimg" class="text-danger"></span>
            </div>
                    <div class="form-group">
                        <label asp-for="PublishedYear" class="control-label"></label>
                        <input asp-for="PublishedYear" class="form-control" />
                        <span asp-validation-for="PublishedYear" class=" text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NrOfPages" class="control-label"></label>
                        <input asp-for="NrOfPages" class="form-control" />
                        <span asp-validation-for="NrOfPages" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BookStore.App/Views/Home/Index.cshtml
@{
    
}

<div class="text-center">
    <h1 class="display-4">Welcome ..</h1>
</div>

BookStore.App/Views/Shared/DelFinish.cshtml
<div class="row">
<div class="col-md-6 offset-3">
    <h1 class="text-info">You just delete the book.</h1>
    </hr>
    <a class="btn btn-outline-success" asp-controller="Book" asp-action="Index">Home</a>
</div>
</div>

BookStore.App/Views/Shared/NotFound.cshtml
<div class="row">
<div class="col-md-6 offset-3">
    <h1 class="text-info">You've reached the end of the internet</h1>
    </hr>
    <a class="btn btn-outline-success" asp-controller="Book" asp-action="Index">Home</a>
</div>
</div>

BookStore.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore.App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Book" asp-action="Index">All Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Author" asp-action="Index">All Authors</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Book" asp-action="Create">Add New Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Author" asp-action="Create">Add New Author</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BookStore
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>